### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by kh411d** [lewie9021/cordova-plugin-video-thumbnail#1]
try to load like this,
$scope.capture =  function() {
  navigator.createThumbnail('x',function(err,imagedata){console.log(err)});
}
Err debug at "navigator.createThumbnail..." line:
 [phonegap] [console.error] TypeError: undefined is not a function

on Cordova 5.2.0, I'm using angularjs

**Comment by lewie9021** [comment]
It's possible that the plugin hasn't been correctly installed. May I suggest adding the plugin within your config.xml file and reinstalling the Android platform?

**Comment by kh411d** [comment]
Hmm still can't figure this out, been trying your suggestion 
Add this manually to config.xml

```
<feature name="VideoThumbnail">
    <param name="android-package" value="com.lewie9021.videothumbnail.VideoThumbnail" />
</feature>
```

reinstall android platform

> ionic platform rm android
> ionic platform add android

Still not resolving the issue, is a bit new for me how could be possible the plugin not installed correctly?

At first, maybe the problem is with the ionic framework so then I try this plugin with plain cordova 5.2.0 project and it seems still can't recognize the plugin

> console.log(navigator.createThumbnail);
> //Giving a null value
> 
> navigator.createThumbnail('x',function(err,imagedata){console.log(err)});
> //Doesn't show any error or anything

I'm using Ionic framework, Cordova 5.2.0, Android Target: Android-22

**Comment by lewie9021** [comment]
I'm not 100% sure how Ionic works, I only use Cordova directly. I usually define my plugins using the _plugin_ element. Since this plugin only currently works on Android, the following is wrapped in a _platform_ element:

``` xml
<platform name="android">
    <plugin name="cordova-plugin-video-thumbnail" spec="2.0.0" />
</platform>
```

Upon reinstalling, Cordova should log out to console that it has found the entry and will attempt to download the plugin from NPM, before adding it to the platform.

Are you testing this plugin directly in the browser or via remote DevTools on an Android device?

**Comment by kh411d** [comment]
I test it using PhoneGap Dev app on play store 
https://play.google.com/store/apps/details?id=com.adobe.phonegap.app

After I upgrade everything phonegap to 5.3.6 and cordova to 5.3.3
and then remove the ionic framework but still can't get this work on phonegap build

nb: plugin element automatically added to config.xml with '--save' argument

> cordova plugin add cordova-plugin-video-thumbnail --save

**Comment by kh411d** [comment]
Ah finally, the problem was with the phonegap app I mention above, I will never use that tool anymore, it's not reliable and give you false error, its working correctly when I run directly on android device using USB

Thanks anyway, sorry for this false alarm
